language: java
deploy:
  provider: heroku
  api_key:
    secure: OCU47IcoasIrFBGAQ5eIQ14WceVuf7j6bWRzFd+u1zEpi9qyi8hUYp6RQKJZ6cEDXgifH6viq03eNGuOWMziLsgG4qCMB4dAIvU6drFdIobeIjZUw60VLyBflMnZ5vYKV/HkMQWqFvLAcbrXpFQC1m22WKuEGf0ZohrBNGdSMBGXVDHB/WmmfkpNsMwX1JnV/8e4lO6yvWTVQqI2QGVVMEmXYGjP5+3cFbQAWAKyUnaOM10KslXGcBuWKhusb+hysa5BZAfc5tO0CeNDvi4HsLIfa6Pn7bO5P5cI3yz4PkS1KPbmzRiCHKiHOdtUNSB0lxCqES9o0Vp5ti7w3zTRRCHq/6odEn3bP7/RZ69/RxMtZJCKksw4KVidS6BdB4KJ0PUlFPSLmfnE+7CqSMvjaHVmywoPh8uLo07HMVSVYch8KfJOoGizIKDOch33ZFdED1xV7HDCQJ67As5DMgMf7vplwjgPoytzIJIWoTtxoCws7fz0RHmQ81AKmbgaa35IuKTWyArIJXscabxKdeuiiKdL+dkM/X4MIpMLhtpG1gtNnKxQev7Lt4YNX6L73YJS4vvenzDCrcgWAyLTlaB09tMpDeJtbcU2bSIgyvSuc/5L4nNir9NPTbc3SJU/bHd7BdZKm8fn8GHs6f4jfmqRW74qkueWsHRRzMwdzteRdxQ=
  app: tictactoe-team-lannisters
  on:
    repo: The-Lannisters/Late-term-Assignment
