language: java
jdk:
- oraclejdk8
env:
- NODE_VERSION=6
install:
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- sudo apt-get install -y curl
- curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install -g yarn
- sudo npm install superagent
- sudo npm install react-dom
- sudo npm install codecov
- "./gradlew"
script:
- "./gradlew check"
- "./gradlew jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash) -t 97716df0-4472-4b46-94da-bf95ded056f5
before_deploy: gradle installDist
deploy:
  provider: heroku
  api_key:
      master:
          secure: ittZxq4PHMVgwKShfQSB3DOvOpokaSvguckb7staRGz9WerimNU44zYhEmfsDDp1rUhDsdGdprRnhQ9sXGEPUDraLMifPO9P+bZn7mH9rznGef/VdEuVB9b/u2KaWVczjGoz0d4iwYAJ5y9NwBxbczulUIFcm6F2NvwUBN+Z8ezzF79w8FXz+Gzj8+qCGQhfzL6fiSgjL8bmDQ4H17qS2a+umIdEh3/GY/CGpG05fgJoBG7GfIUZf8AcqcPXGhsbZXAYvhPWCoKsvc05ix937nKgyhsMg81/iFWt5YNcTXARiuH0aZR1wAtFJKp00JwSFQ7JINhYHEqnOMIYSaKq+ewQlUV3eEaxX/pYA/aVJSkkPwVwTXIx+YdtRe5O0tWgZdDllCzzifwsKtAuF3iB1DUPIe7xWOLL+KiK1S0IYJFP7fseorw4Ofd1boUJm+aHmZHiPlP6sU+jy0iDb54kUcP56zIy1EhUCf9hRty+wV/+35JTVrnhs3x/z59+QsvjFuVWCC3zo9jlY2Bq1RIJbtuY/MXskrh72AGdy3yjsBF8h+pPHYzKpnSNx5ANcfxXjug+IGA6uENpQMYNL+ILJmbwkmXx2hAxEJ9bz2zXg89M7V36+VoPJ0WwnUeFz1FDYpq42DDmAbA6x52997LzQmo/xC6AtbiIGiEYMnzsscE=
          Presentation:
              secure: XeeYWXhhLeSyTtKNG24cPUFoMg7wc45QO9RefhL7H4bGtVjmKCE4qDNfbyY73NKNMW1VpHN2xF2ai6v5mkYrazoA0bazasxvrZhAziz5x0UV2+Mz0iJzvAIgqGDrxg5q6obfGQ4S+5UQ70Iq21DlIOyGUOXXHk84+UuGwD7iYvIko88qY2/fd6eFwL8rrrYMkusu/xBeI7IGeL28ds6ShMssaXslimAxIJ5zJsRDnze8vT8VDODjztE/fAmcO9OdBDkknVyZLU1PIGKwduhfYcphv3r9n2ZvENyJe7Y3N+SBw+95a2QqGvUXUDE0nh+UoIRogwbz34fQ8pzSiV/3egs0ThfLfCxIZD7jgvJ2wJkXPh6pFr248SBM8yjgS717iYdkfmYZhASFkc4lkmx0XKm0T5mQ2WrUK3aIvUxrzmTp57fYl5eJP6bSU3l6pO7tnLSpPxspsNFLOsTCof0UAN1a5HHqqMdI2O3zGBYp5krI2H872N5qBY8bj7hgKu/F/QQBqztVZIMzxRDazJza/DtO4U6eqT9k1wGCgfj5wHPLf1FHoOmTm2BzhrS1dWtHkiFbLHIfwo6dv3HzPu/n5YpQ6erRWcx1ECt2owHrsqSL9It+1u5xJ/6uxBl3qpce3O2cqMRoU1nLKKnza8zA2JV+gtNCj1dX5njnC2xf8rg=

  app:
    master: the-lannisters-tictactoe
    Presentation: tic-tac-toe-testing
