language: java
jdk:
- oraclejdk8
env:
- NODE_VERSION=6
install:
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- sudo apt-get install -y curl
- curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install -g yarn
- sudo npm install superagent
- sudo npm install react-dom
- sudo npm install codecov
- "./gradlew"
script:
- "./gradlew check"
- "./gradlew jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash) -t 97716df0-4472-4b46-94da-bf95ded056f5
before_deploy: gradle installDist
deploy:
  provider: heroku
  api_key:
    master:
      secure: t936P30CExd+ndiDUUMiTCDCdhYMMTaTdz5ZHgmMKvLKcW4bQ+FNxvmy5pAAcp6Y9qrfUQFVnauWoaNtkfAZVu60VdLRdLTbasGff0/YvmR4kq0PeeRV3f9WVWrWs/BFSyC9pI8zW7rYR9SxTT1s5Cf81gCQsPdLuQVt6wxviT3D4K9GZmG79Rilu5ySZYrE6rJL/WkL2NPTYtonmFlIslDIEu2XiQS+k0Z3sU7upLCM80BUNDfSEdGonJP1AAPr7kCQw5WtCiIomp08RUpOKlDGRwJghflEFOEe3ccYUHnDEUCwouZEqTlNYqzfDURQh0w3CqJnPZYKc9REpIH78dUvxKrChIl0ks89r+7ijagoGxtrfr262pjOVxGLV0hBuW02jBukKy+AnK7Ok6VpIM8POWKzf2iTfVKwwhBEHTW3IJS4UdD+RJStK5lSCCTmmja0YrOJuAblbpDd0ZB79+5sndU45CHfQtFffZ4z+5fdkvEKHnHkSXdbCDGOFyBNLRox5gVhDPLlYAAGxy5xARobATYL8R3d0AG3KdTvNF8sO9IdJ8Sw0q3Rooq7mB/9i4kn99mtP7nxYzIqOWhZBV7GHqq1yiPtK3woIWC5WKDlnhnhQ+NpI7Z6Jr88+7+3lrWCUbw3G6cLsr/l5DVdVfuzlUWWX9xUhAg6zrZXbsg=
    Presentation:
      secure: LnyMP7aAEp0p6OFvoxmA4CQN1bvhIT2oJ51+bvO0hLaAfi2wEE7m9yB/KqhQMcNibSK91dd+THBVQiND9M6Psbgt0NuWyxHVgPMPBGvmwQB3cXHBDwd1N8UIPBCzvQgebIQtzJ0UkSjRj/ebWEZU5p702KkP/IJcUiKKyYrDXYu1pG7JnpTSbPM3cX64IOsrF6LgCgsLEYGsbKkBKO+NPVvwOSlZDqi5mT9jUtHq4GcWWkPRxPU+ZJtvvDaYBagKXumiHKjt6HTfW9UL9KsaQjrkNkI5XYj0IiDMRDU9Xv0bp/27Zhrfn8R/JXwWs8vgu34ng95Rd/LVT0YDX2fTnItk2vK5Tx2WCKzNzh6lX65Uz93KHz0+2L9QLZ/JfSrDueJSp7F8ga81AVDfyS+cPSiGryimqDxu33Ystdp9yedu7Qb3TjGe5oLuKn+36Xdnht2YCtMpi+eCsArAPdL6SSTJcw2qwIYP5PcAhdxqMvLxoyJ1zuEqlpvK8dIoJYSlVR8OkdtG1t73dmTtkA0urQzhBQP7KQFo/W/VwcuwUacBnnu2E3qVn0Rl6cJgvce4jwH2jXcF7Ugp+t+V4aBTy0k2u8xYuUoIa+btG5MztJH0cmCyfUwhZJXFXBC1bwq/CVfIcv8RHvVaWu1rXO5H29EhrNfl81dY56rhlcl02TA=
  app:
    master: the-lannisters-tictactoe
    Presentation: tic-tac-toe-testing
