language: java
deploy:
  provider: heroku
  app: tictactoe-team-lannister
  api_key:
    secure: zPq2tvhNOw7LRoKPywhFqRDq8yT5Lrkt33vjcRi/N4MBHeXhRI3azxLTB5I2QczcYABSCEecMxGn7ywqZhPBL7oaT70ewrH7jY4iXaN/OnyNhjtlCz/52QbJ1dlPQCodfiThwasHhwM30aobey6Gb0YqDPX7D0ar+uGFmAC03Q2h0hjRpmltS13hg5YaSonUXYeHOuUq+oFka97CNd3KJxGmd4X1r1DVcNjbo8HMIXB4G8K8nez/r/fi4zbmNsYQN4MM4/18gXcKpDa+U4jCkhIEQOPUepvfIsLc6Njo38P0pTrXYeWUr0PRyRQEl1e8gJNuVb70WSiZ08rNMAJGMiL3n5RIWS9oyGF50M/wW/o87tAdIV+y2bWIsQ+OMJ4ZGCtqZLIyHHvZuD71NOhOXm03okBJBIFK1sYEGnlNySTy68OSUZrBNGHHf2SwNwvVZElvgbSjX5wZCniH24z2KGVG/gthkdwOztkptLDedh2O/F0olNXG7IOgZPV0rdopDM56LFEY7fnpdnH2cwsvjhdgYhVhNMZ8EtQo3Scq6rJgOxknPNncmiFKWQdIe5NsgiVrwd1mSyGP47BIfJLNBHSeflfb1afrPL3uJMBwfWbUm5MvmGE27Tck6yBm+RiRnDubChYB5CU/CWnWss4wcYdccN3pflFSf2abevzxzMo=
