language: java
deploy:
  provider: heroku
  app: tictactoe-team-lannister
  api_key:
    secure: GreGLYV/1+OQezXWCN358el8JlueunJlVcMl7LXXiIDgrocUIKtgEkBnuUgsucx53x8tj840o9vzrLQTyV77Wkibg/z472AGvTv2m5Q6CN1rujtSiiWf8Pond7D8wvYtfqoarreYBLu3lOrIfxIlm8CHB77LkFMclFHbAiCPz5/HaJAKFRbqfBHC+b90gpJqo/Qj6gA87UDjbNpEY2iKqfV0nyqkgTYERVjHD091LNAwDQ3b6O7WFKl8r0RXPlqAvhakHicgRP6cKOJm9n35TYVF4LpHRe7DtHfcSF427s4uku6Ntkuzzcs5Gqi3LM4BcDQS9uswNZHOAsbw1B9R/6lDmv//v5YBxj+t4lbkMxYy8Ldw89cJEke4jcQTU7XJ4aOV2MiyeM/qDQLHS8xKwJpUKenkKOGYHErgnBe9Prju0uPqQP1o6Cv9rdMP4g66U1l63xJdxYOP1ky1p6YRNI9jGHldJZXDNwf6uHuZIleIx/ggpH2HjphT+zmMm75FEF1ebU7E8Zn3OwRbDgURi/8C+wcnWjt4tlClL/1p6Gz/mYKtfRTLqRA1Blz6lIYv86Vcovvo+FkyzVqCYGTSqv8IX/x9C1qPq2Q6SwCFI09eoDFLDfQyli5DamMTTjKKhIFtIypYg0YdoiEVVirmEwT1vD/Yx8TpEMKBCIbqCQg=
