language: java
deploy:
  provider: heroku
  app: tictactoe-team-lannister
  api_key:
    secure: PAKRCxvj3U0yJZ1wGII9tLVdsU8FYTd+VmfY++mWGHzQQynBXuqZFbhvsv3Zuv7Tad4iHVi067CviYourXNg5pilVa3DYKyaoQ5rv3lkNzvNmjNe3unkM0LFAiHPTpZxQfECtcbYp51wX6JiQVcWf8BUeOvcFp+F4u2BvUDbAfDSEIDdjHJJJfJI7bk10eToNIprqnyogsqqoNI79lS8Rw5/MuyJ3rnGgiBQqZ1L6yXAjBhrOXKeortbEfaXOzcL1aa0KnWzeK+n34BuT0fJWA6azQAawU2DezRPYPK1LuQM5zeYxgwq6VH0Asoa2k877INVYZv9WTedE8Sv9DCbbZU0FhrhqjMpWNC903sb0u+R8tgZf1rPLSt2k+/6A7bV2KBMLh7+G+rj/llf2LQOqBFl1yKjl/tdx+WuqCwYxgojD6cp9+X3hRe9H19cX4S6y1/8yna+eyr1j+6vv/UO4odCkmoIKmZ4x/0RlLEfvklQ/AlUrRpr1XZ1Tz2G1c0r6IKSMxrPgXQ/VxZflv7y9EblFCRIotXjkhRveNbo6jCNJ0o6z/dxhTkZMD9CjBWeHXbQpRoLHtiiGOt3o9BmqPwqa25qAUNOZ8GD2tPi0jhkKX+Xv8eM78CJy6FfnurTlsVqdDdQbiLsyXyQP3OoIgVHplI544OpK5UFESyo81c=
