language: java
deploy:
  provider: heroku
  app: tictactoe-team-lannister
  api_key:
    secure: uYa2lyTOm+dtJN1eN62tzb/NkVG07UUPuSjKgjskHt5iSoAp384zAZzoMDO/LVTnfPqHWbKqvwiRcB6OMkA2vUuqaUMZUlnHhTxeG7lnovTT588Oez3kiL5cM6FzBdokCqhj3Fhilm0vUGX4IZ8gLujko47XYU9s+Vl8FsLMwYBzzXgRfbz+Mz4kZUDFDh40pfZY2cdXtBiEeBlJAnah0khtDwFyZ3By0WPWHzYL8nQq4ge9Tkbjn4mWFHKkcg+Jlst1jcmeNA3oGJqCMKKVdG5ya8Ol1z6z5HojJBrI02uXGiaQXqTj9ELY62Euey+hF8kaPwGHrSFgrnn+XnB3IjjSGnnCPPghsjyG/SeUcGOmnM1/71TKNBb9J2PiUaDeQdlWVR+jeY7yUNs2w8ED3aupDlOHRtd3Yi1EzfGhXqqOWB+Oim6DCAxpTBNb3b40Ryoo3rbZZE394tbxKPmnirpngNThN5W++D1GnLBunILi+AHaAgQRh17dFzbq+t+JTFqUTJ5W2HWGFnumIm5o9kLeoXpPAbVh0HzgmiVp0ha932RPlkbXgdNrfqq5nnchDFF3bkD/lPXrSej1MnTh8NG7WmfmNx77QwZ1Tdy8FqOq3ow+42279K/5eJNiQ9H8GJ56OspfJzKp0LWFvSExVW/j8R8+OrtpHgydI4m4G9k=
