language: java
deploy:
  provider: heroku
  api_key:
    secure: DfzEt3RXv2Zlkotnqb0cKHqB5Y+jvFbQKtVUDUQIoLZiwGWTh6jgolipJtDC2b1hDn9SDLT4LeXOTHVz1HWAw+hUhu0GQS/hA5qrZ9oEL2Jdv4jHVxA5Ci/3bH6hMymlsEBUTDcrQFuyRkyum2CiwNccc6EUu5GtMvt+Rke5IyBZqAIV9ALqrzLIxxAvY6WSfblpsUHdVmV4Bei1GnEDvBHZ2Q+MJwfScJNCXdQPSEJ0eYvbZIXwXL8kL/qD4ah8pJJJh00j3NWn59MYnedYW4zmD6wnQzBew2bGrBH9OID9wzBTT1yb57ET6+2mIIIBNaQSyEaurcTvGAE4hqL8te02SqtzpfUfjiZVfCOTgJRWdG88yCvD2VaqS/n3qio40rm098kkiV+eulPIQNmqRHEAPrE8wjmoR7iuPlLMYoOKLNblEvk+G7AyA3meuoPEHB+zV4z+hDX6WsgC/Zvhm0HGd2iujMNvD5ii2QdFdeDJQNpxMsVDfkYURcYIlCdPgOUShB3z0EL5AzkGg/lK67qXCg29+8d+UN1qhS91H/F29/LT8hwkBYwswI8PnPQphjD47+i0sjhcFFBIV4NR6WAnp34QvqLW1Du7x06lu54SPHm8Dkz4nLyIMFfZ/hCDQUzcjYBW0/88vtvCDAb4FLOGATp6oJyQYsgST81skZA=
  app: Late-term-Assignment
  on:
    repo: The-Lannisters/Late-term-Assignment
